[[redirects]]
    from = "/v1"
    to = "https://amseeyou-v1.netlify.app"

[[redirects]]
    from = "/v2"
    to = "https://amseeyou-v2.netlify.app"
    status = 200

[[redirects]]
    from = "/v3"
    to = "https://amseeyou-v3.netlify.app"
    status = 200
    force = true